spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?serverTimezone=UTC
      username: root
      password: dobi0108
      #初始化连接
      initial-size: 20
      #最大连接数量
      max-active: 50
      #最小空闲连接
      min-idle: 10
      #超时等待时间
      max-wait: 5000



mybatis-plus:
  #如果mapper映射文件与mapper接口不在同一级那么需要进行制定
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ldb.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
